#!/bin/sh
set -v

./make_data benchmarks-carol-georgia-*.txt
./lines.gnuplot && mv lines.svg carol-georgia.svg

./make_data benchmarks-carol-tnr-*.txt
./lines.gnuplot && mv lines.svg carol-tnr.svg

./make_data benchmarks-thesis-georgia-*.txt
./lines.gnuplot && mv lines.svg thesis-georgia.svg
