#!/bin/zsh

go() {
    src=$1
    pid=$( grep '^multitime' $src | cut -d. -f2 )
    output=$2
    ./make_one_plot $src $pid && mv bars.svg $2
}

go benchmarks-carol-georgia-10.txt carol-georgia-10.svg
go benchmarks-carol-georgia-11.txt carol-georgia-11.svg
go benchmarks-carol-georgia-12.txt carol-georgia-12.svg
go benchmarks-carol-georgia-13.txt carol-georgia-13.svg
go benchmarks-carol-georgia-14.txt carol-georgia-14.svg
go benchmarks-carol-georgia-15.txt carol-georgia-15.svg
go benchmarks-carol-georgia-16.txt carol-georgia-16.svg
go benchmarks-carol-georgia-17.txt carol-georgia-17.svg
go benchmarks-carol-georgia-18.txt carol-georgia-18.svg
go benchmarks-carol-georgia-19.txt carol-georgia-19.svg
go benchmarks-carol-georgia-20.txt carol-georgia-20.svg

go benchmarks-carol-tnr-10.txt carol-tnr-10.svg
go benchmarks-carol-tnr-11.txt carol-tnr-11.svg
go benchmarks-carol-tnr-12.txt carol-tnr-12.svg
go benchmarks-carol-tnr-13.txt carol-tnr-13.svg
go benchmarks-carol-tnr-14.txt carol-tnr-14.svg
go benchmarks-carol-tnr-15.txt carol-tnr-15.svg
go benchmarks-carol-tnr-16.txt carol-tnr-16.svg
go benchmarks-carol-tnr-17.txt carol-tnr-17.svg
go benchmarks-carol-tnr-18.txt carol-tnr-18.svg
go benchmarks-carol-tnr-19.txt carol-tnr-19.svg
go benchmarks-carol-tnr-20.txt carol-tnr-20.svg

go benchmarks-thesis-georgia-01.txt thesis-georgia-01.svg
go benchmarks-thesis-georgia-02.txt thesis-georgia-02.svg
go benchmarks-thesis-georgia-03.txt thesis-georgia-03.svg
go benchmarks-thesis-georgia-04.txt thesis-georgia-04.svg
go benchmarks-thesis-georgia-05.txt thesis-georgia-05.svg
go benchmarks-thesis-georgia-06.txt thesis-georgia-06.svg
go benchmarks-thesis-georgia-07.txt thesis-georgia-07.svg
go benchmarks-thesis-georgia-08.txt thesis-georgia-08.svg
go benchmarks-thesis-georgia-09.txt thesis-georgia-09.svg
go benchmarks-thesis-georgia-10.txt thesis-georgia-10.svg
